CREATE TABLE users (
	user_id SERIAL PRIMARY KEY NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(16) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	image VARCHAR(255),
	create_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);