CREATE TABLE users (
	userId serial PRIMARY KEY NOT NULL,
	isActive VARCHAR(255) NOT NULL DEFAULT true,
	isDeleted VARCHAR(255) NOT NULL DEFAULT false,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(16) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	image VARCHAR(255),
	create_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);